name: Rerun Flaky Live Tests
on:
  workflow_run:
    workflows: ["CI Pipeline", "CI Security"]
    types:
      - completed
jobs:
  rerun_flaky_tests:
    name: Rerun Flaky Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.run_attempt < 5 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rerun flaky tests
        uses: actions/github-script@v7
        with:
          script: |
            const { rerunFlakyTests } = await import('${{ github.workspace }}/.github/workflows/scripts/rerunFlakyTests.js')
            await rerunFlakyTests({ github, context })
