name: 'Master Merge'

on:
  push:
    branches:
    - master
  workflow_dispatch:

env:
  TGS_DOTNET_VERSION: 8
  OD_MIN_COMPAT_DOTNET_VERSION: 7

jobs:
  master-merge:
    name: Master Merge
    runs-on: ubuntu-latest
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '${{ env.TGS_DOTNET_VERSION }}.0.x'
        dotnet-quality: ${{ env.TGS_DOTNET_QUALITY }}

    - name: Build Checkout
      uses: actions/checkout@v4
      with:
        path: temp_workspace

    - name: Restore
      run: |
        cd temp_workspace
        dotnet restore

    - name: Build ReleaseNotes
      run: |
        cd temp_workspace
        dotnet build -c Release -p:TGS_HOST_NO_WEBPANEL=true tools/Tgstation.Server.ReleaseNotes/Tgstation.Server.ReleaseNotes.csproj

    - name: Generate App Token
      run: |
        cd temp_workspace
        dotnet run -c Release --no-build --project tools/Tgstation.Server.ReleaseNotes --token-output-file ${{ runner.temp }}/installation_secret.txt ${{ secrets.TGS_CI_GITHUB_APP_TOKEN_BASE64 }}
        echo "INSTALLATION_TOKEN=$(cat ${{ runner.temp }}/installation_secret.txt)" >> $GITHUB_ENV
        rm ${{ runner.temp }}/installation_secret.txt
      env:
        TGS_RELEASE_NOTES_TOKEN: ${{ secrets.DEV_PUSH_TOKEN }}

    - name: Main Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ env.INSTALLATION_TOKEN }}

    - name: Merge master into dev
      uses: robotology/gh-action-nightly-merge@14b4a4cf358f7479aa708bee05cf8a794d6a2516 #v1.5.0
      with:
        stable_branch: 'master'
        development_branch: 'dev'
        allow_ff: true
        allow_forks: true
        user_name: tgstation-server-ci[bot]
        user_email: 161980869+tgstation-server-ci[bot]@users.noreply.github.com
        push_token: INSTALLATION_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
