name: Master Merge

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  TGS_DOTNET_VERSION: 8
  TGS_DOTNET_QUALITY: ga

jobs:
  master-merge:
    name: Master Merge
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        id: app-token-generation
        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token-generation.outputs.token }}

      - name: Merge master into dev
        uses: robotology/gh-action-nightly-merge@14b4a4cf358f7479aa708bee05cf8a794d6a2516 #v1.5.0
        with:
          stable_branch: master
          development_branch: dev
          allow_ff: true
          allow_forks: true
          user_name: tgstation-server-ci[bot]
          user_email: 161980869+tgstation-server-ci[bot]@users.noreply.github.com
          push_token: INSTALLATION_TOKEN
        env:
          GITHUB_TOKEN: ${{ steps.app-token-generation.outputs.token }}
